In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np

## 배열의 곱셈

In [3]:
la = [[1.,2.],[3.,4.]] # 파이썬 리스트
la

[[1.0, 2.0], [3.0, 4.0]]

### 파이썬 리스트에 곱연산을 하면 배열을 복사한다.

In [4]:
la*3

[[1.0, 2.0], [3.0, 4.0], [1.0, 2.0], [3.0, 4.0], [1.0, 2.0], [3.0, 4.0]]

In [5]:
aa = np.array(la)
aa

array([[1., 2.],
       [3., 4.]])

### numpy 배열에 곱연산을 하면 각 요소에 곱셈을 한다
#### >> 병렬적으로 빠르고 쉽게 연산이 가능하다

In [6]:
aa*3

array([[ 3.,  6.],
       [ 9., 12.]])

## 배열의 덧셈/뺄셈

In [7]:
aa = np.array([[1.,2.,3.,],[3.,4.,5.]])
aa

array([[1., 2., 3.],
       [3., 4., 5.]])

In [8]:
aa + 10

array([[11., 12., 13.],
       [13., 14., 15.]])

In [9]:
aa + np.array([10,20,30]) # 각 열에 10, 20, 30씩 더한다 >> Broadcast된 것

array([[11., 22., 33.],
       [13., 24., 35.]])

In [10]:
aa + np.array([[10],[30]]) # 1행에 10, 2행에 30씩 더한다  >> Broadcast된 것

array([[11., 12., 13.],
       [33., 34., 35.]])

In [11]:
# aa + np.array([10,10]) # [x] 확장(Broadcast)이 불가능하기 때문에 에러 발생

## 행렬의 곱셈 : 내적 : np.dot(arr1,arr2)

## 이 때, arr1의 열의 수와 arr2의 행의 수가 무조건 같아야 한다.

In [12]:
aa = np.array([[1,10],[2,20],[3,30]])
bb = np.array([[1,2,3],[1,2,3]])

In [14]:
np.dot(aa,bb)

array([[11, 22, 33],
       [22, 44, 66],
       [33, 66, 99]])

# Tensor 생성하기
## - tf.constant() : Tensor 타입 객체 생성 >> 배열의 원소 변경이 불가능
## - tf.Variable() : Variable 생성 >> assign()함수로 배열 원소 변경 가능

(배열 전체 갱신은 둘 다 가능)

In [16]:
tc = tf.constant([[1,2],[3,4]])
print(tc,", ",type(tc))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) ,  <class 'tensorflow.python.framework.ops.EagerTensor'>


In [27]:
ta = tf.Variable([[1,2],[3,4]])
print(tc,", ",type(tc))

tf.Tensor(
[[-99 -98]
 [-97 -96]], shape=(2, 2), dtype=int32) ,  <class 'tensorflow.python.framework.ops.EagerTensor'>


In [19]:
t2 = ta * 10
t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

### 배열 전체 갱신

In [20]:
ta = ta+100
tc = tc-100

### 배열 원소 변경 - Variable 객체만 가능

In [25]:
#ta[0,0] = -1 #[x] 할당 연산자는 사용 불가

In [30]:
ta[0,0].assign(-1) # assign() 함수로만 변경 가능

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[-1,  2],
       [ 3,  4]])>

In [32]:
# tc[0,0] = -1 #[x]
# tc[0,0].assign(-1) #[x]

## Tensor의 연산

덧셈/뺄셈 : tf.add(), tf.subtract or +, -

곱셈 : tf.multiply() or *

내적 : tf.matmul()

등등...

In [35]:
tb = tf.Variable([[2,3,3],[1,2,2]])
tf.matmul(ta,tb)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0,  1,  1],
       [10, 17, 17]])>