In [1]:
import tensorflow as tf

In [6]:
import pandas as pd
import numpy as np

## 배열의 곱셈

In [12]:
la = [[1.,2.],[3.,4.]] # 파이썬 리스트
la

[[1.0, 2.0], [3.0, 4.0]]

### 파이썬 리스트에 곱연산을 하면 배열을 복사한다.

In [8]:
la*3

[[1.0, 2.0], [3.0, 4.0], [1.0, 2.0], [3.0, 4.0], [1.0, 2.0], [3.0, 4.0]]

In [9]:
aa = np.array(la)
aa

array([[1., 2.],
       [3., 4.]])

### numpy 배열에 곱연산을 하면 각 요소에 곱셈을 한다
#### >> 병렬적으로 빠르고 쉽게 연산이 가능하다

In [10]:
aa*3

array([[ 3.,  6.],
       [ 9., 12.]])

## 배열의 덧셈/뺄셈

In [13]:
aa = np.array([[1.,2.,3.,],[3.,4.,5.]])
aa

array([[1., 2., 3.],
       [3., 4., 5.]])

In [14]:
aa + 10

array([[11., 12., 13.],
       [13., 14., 15.]])

In [22]:
aa + np.array([10,20,30]) # 각 열에 10, 20, 30씩 더한다 >> Broadcast된 것

array([[11., 22., 33.],
       [13., 24., 35.]])

In [23]:
aa + np.array([[10],[30]]) # 1행에 10, 2행에 30씩 더한다  >> Broadcast된 것

array([[11., 12., 13.],
       [33., 34., 35.]])

In [21]:
# aa + np.array([10,10]) # [x] 확장(Broadcast)이 불가능하기 때문에 에러 발생

## 행렬의 곱셈 : 내적