# Numpy

## ndarray

In [1]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3])
print('1차원 데이터 arr1.shape:',arr1.shape)
arr2 = np.array([[1,2,3],[2,3,4]])
print('2차원 데이터 arr2.shape:',arr2.shape)
arr3 = np.array([[1,2,3]])
print('2차원 데이터 arr3.shape:',arr3.shape)

1차원 데이터 arr1.shape: (3,)
2차원 데이터 arr2.shape: (2, 3)
2차원 데이터 arr3.shape: (1, 3)


In [6]:
seq_arr = np.arange(10)
zero_arr = np.zeros((3,2))
one_arr = np.ones((3,2))

### reshaping

In [8]:
arr1 = np.arange(10)
arr2 = arr1.reshape((2,5))
arr3 = arr1.reshape((5,-1))

In [9]:
print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### indexing

In [10]:
arr1d = np.arange(1,10)
arr2d = arr1d.reshape((3,-1))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### sort

In [11]:
org_arr = np.array([3,1,9,5])
org_arr

array([3, 1, 9, 5])

In [12]:
# np.sort()
sort_arr1 = np.sort(org_arr)
print(sort_arr1) # 1 3 5 9
print(org_arr) # 3 1 9 5 >> 원본 수정되지 않음

[1 3 5 9]
[3 1 9 5]


In [13]:
# ndarray_obj.sort()
org_arr.sort()
print(org_arr) # 1 3 5 9 >> 원본 수정

[1 3 5 9]


# Pandas

In [14]:
import pandas as pd

In [20]:
titanic = pd.read_csv('../data/titanic_train.csv')
titanic.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [21]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [22]:
titanic.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [23]:
titanic_pclass = titanic['Pclass']

In [24]:
# Series
s1 = pd.Series([1,3,5,7,9])
print(s1.shape)
print(s1)
print(s1.index)

(5,)
0    1
1    3
2    5
3    7
4    9
dtype: int64
RangeIndex(start=0, stop=5, step=1)


In [25]:
titanic_age = titanic['Age']

In [27]:
titanic_age.sum()

21205.17

In [32]:
1 + 2 + 3 + np.nan # 직접 산술 연산을 할 때는 NaN 포함 시 무조건 NaN 반환

nan