In [2]:
import numpy as np

# ndarray

In [2]:
nda1 = np.array([1,2,3])

In [3]:
print(type(nda1))
print(nda1.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
b = np.array([[1,2,3],[1,2]])

C:\Users\songkyu\anaconda3\envs\ITConsulting\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [7]:
print(b)
print(b.shape)

[list([1, 2, 3]) list([1, 2])]
(2,)


In [9]:
c = np.array([[1,2,3],[1,2,3]])
print(c)
print(c.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [11]:
d = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(d)
print(d.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


In [6]:
e = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(e)
print(e.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


# ndarray dtype

In [4]:
ndadtype = np.array([1,'2','hello'])
print(ndadtype)
print(ndadtype.dtype)

['1' '2' 'hello']
<U11


In [7]:
e.astype('str')

array([[['1', '2'],
        ['3', '4']],

       [['5', '6'],
        ['7', '8']],

       [['9', '10'],
        ['11', '12']]], dtype='<U11')

# ndarray 생성하기

In [8]:
np.zeros(2)

array([0., 0.])

In [11]:
np.zeros(0).shape

(0,)

# reshaping

In [12]:
re = np.arange(10)
re

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
re2 = re.reshape((2,5))
re2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
re3 = re2.reshape((2,1,5))
re3

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [17]:
# re2.reshape((2,1,1)) # [x]

ValueError: cannot reshape array of size 10 into shape (2,1,1)

In [18]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
array2d = array3d.reshape(-1,1)
array2d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [23]:
array1d = array2d.reshape(-1)
array1d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
np.arange(9).reshape((3,1,3)).reshape((-1,1)).tolist()

[[0], [1], [2], [3], [4], [5], [6], [7], [8]]

# indexing

In [31]:
array2ds = np.arange(9).reshape((3,3))
array2ds

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
array2ds[[0,1],[1,2]]

array([1, 5])

In [35]:
array2ds[[0,1,2],[2,0,1]]

array([2, 3, 7])

In [38]:
arr2ds = np.arange(1,10).reshape((3,3))
arr2ds[:,[2,0,1]].tolist()

[[3, 1, 2], [6, 4, 5], [9, 7, 8]]

# sorting

In [41]:
sortarr = np.arange(10)
sortarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.sort(sortarr,axis=0,kind='quicksort')[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
sortarr2d = sortarr.reshape((2,-1))
sortarr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
np.sort(sortarr2d,axis=0)[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])