In [10]:
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable
from torch.nn import Parameter
from torch import Tensor
import numpy as np
import pandas as pd

In [2]:
x = torch.Tensor(np.arange(1,11).reshape(-1,1))
y = torch.Tensor(np.arange(1,11).reshape(-1,1))

In [3]:
class Model(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Model,self).__init__()
        self.seq = nn.Sequential(nn.Linear(input_dim,output_dim),
                                nn.ReLU())
    def forward(self,x):
        out = self.seq(x)
        return out

In [4]:
model = Model(1,1)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

In [5]:
epochs = 500
for epoch in range(epochs):
    pred = model(x)
    loss = criterion(pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
model.eval()
with torch.no_grad():
    pred = model(x)
    loss = criterion(pred, y)
    print('loss:',loss.item())

loss: 0.0033179917372763157


In [6]:
pred

tensor([[ 0.8941],
        [ 1.9124],
        [ 2.9307],
        [ 3.9490],
        [ 4.9673],
        [ 5.9856],
        [ 7.0040],
        [ 8.0223],
        [ 9.0406],
        [10.0589]])

In [9]:
y_np, pred_np

(array([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], dtype=float32),
 array([[ 0.8941051],
        [ 1.9124138],
        [ 2.9307227],
        [ 3.9490314],
        [ 4.96734  ],
        [ 5.985649 ],
        [ 7.0039577],
        [ 8.022266 ],
        [ 9.040575 ],
        [10.058884 ]], dtype=float32))

# 101~110

In [18]:
x_test = torch.Tensor(np.arange(101,111).reshape(-1,1))
y_test = torch.Tensor(np.arange(101,111).reshape(-1,1))

In [19]:
class Model(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Model,self).__init__()
        self.seq = nn.Sequential(nn.Linear(input_dim,5,bias=True),
                                nn.ReLU(),
                                nn.Linear(5,3,bias=True),
                                nn.ReLU(),
                                nn.Linear(3,output_dim,bias=True),
                                nn.ReLU())
    def forward(self,x):
        out = self.seq(x)
        return out

In [20]:
class RMSELoss(nn.Module):
    def __init__(self):
        super(RMSELoss,self).__init__()
        self.mse = nn.MSELoss()
        
    def forward(self,yhat,y):
        return torch.sqrt(self.mse(yhat,y))

In [22]:
model = Model(1,1)
criterion = RMSELoss()
optimizer = optim.Adam(model.parameters())

In [23]:
epochs = 500
for epoch in range(epochs):
    pred = model(x)
    loss = criterion(pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
model.eval()
with torch.no_grad():
    pred = model(x_test)
    loss = criterion(pred, y_test)
    print('loss:',loss.item())

loss: 0.1049417033791542


In [24]:
pred_np = pred.detach().numpy()
y_test_np = y_test.numpy()
from sklearn.metrics import r2_score
r2_score(y_test_np,pred_np)

0.998665119910782