# Encoding

In [2]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

items = ['Tv','냉장고','전자렌지','선풍기','컴퓨터','믹서']

In [6]:
# Label Encoding
le = LabelEncoder()
le.fit(items)
le_items = le.transform(items)
print('인코딩된 값:',le_items)

인코딩된 값: [0 1 4 3 5 2]


In [7]:
# 디코딩
print(le.inverse_transform(le_items))

['Tv' '냉장고' '전자렌지' '선풍기' '컴퓨터' '믹서']


In [8]:
import numpy as np
# OneHot Encoding
ohe = OneHotEncoder()
items2d = np.array(items).reshape((-1,1))
items2d

array([['Tv'],
       ['냉장고'],
       ['전자렌지'],
       ['선풍기'],
       ['컴퓨터'],
       ['믹서']], dtype='<U4')

In [11]:
ohe.fit(items2d)
ohe_items = ohe.transform(items2d)
ohe_items.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.]])

In [12]:
ohe.inverse_transform(ohe_items)

array([['Tv'],
       ['냉장고'],
       ['전자렌지'],
       ['선풍기'],
       ['컴퓨터'],
       ['믹서']], dtype='<U4')

In [14]:
# pandas pd.get_dummies()
import pandas as pd
np.array(pd.get_dummies(items))

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

# Feature Scaling

In [16]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris_data = iris.data
iris_target = iris.target
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
print('features 평균')
print(iris_df.mean())
print('--------------')
print('features 분산')
print(iris_df.var())

features 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
--------------
features 분산
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [24]:
print('features 최솟값')
print(iris_df.min())
print('----------------')
print('features 최댓값')
print(iris_df.max())

features 최솟값
sepal length (cm)    4.3
sepal width (cm)     2.0
petal length (cm)    1.0
petal width (cm)     0.1
dtype: float64
----------------
features 최댓값
sepal length (cm)    7.9
sepal width (cm)     4.4
petal length (cm)    6.9
petal width (cm)     2.5
dtype: float64


In [20]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(iris_df)
iris_ss_scaled = ss.transform(iris_df)
# iris_ss_scaled는 ndarray 임.
iris_df_ss_scaled=pd.DataFrame(data=iris_ss_scaled,columns=iris.feature_names)
iris_df_ss_scaled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [28]:
iris_df_ss_scaled.mean()

sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

In [29]:
iris_df_ss_scaled.var()

sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [25]:
# MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit(iris_df)
iris_mm_scaled = mm.transform(iris_df)
# iris_ss_scaled는 ndarray 임.
iris_df_mm_scaled=pd.DataFrame(data=iris_mm_scaled,columns=iris.feature_names)
iris_df_mm_scaled

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             0.222222          0.625000           0.067797          0.041667
1             0.166667          0.416667           0.067797          0.041667
2             0.111111          0.500000           0.050847          0.041667
3             0.083333          0.458333           0.084746          0.041667
4             0.194444          0.666667           0.067797          0.041667
..                 ...               ...                ...               ...
145           0.666667          0.416667           0.711864          0.916667
146           0.555556          0.208333           0.677966          0.750000
147           0.611111          0.416667           0.711864          0.791667
148           0.527778          0.583333           0.745763          0.916667
149           0.444444          0.416667           0.694915          0.708333

[150 rows x 4 columns]

In [26]:
iris_df_mm_scaled.min()

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

In [27]:
iris_df_mm_scaled.max()

sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

### 스케일링 주의점

In [32]:
import numpy as np
mmscaler = MinMaxScaler()
train_arr = np.arange(11).reshape(-1,1)
test_arr = np.arange(0,6).reshape(-1,1)
print(train_arr,test_arr,sep='\n')

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [33]:
mmscaler.fit(train_arr)
train_mm_scaled = mmscaler.transform(train_arr)
train_mm_scaled

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [40]:
# 학습 데이터 기준의 MinMaxScaler로 transform한 경우
test_mm_scaled = mmscaler.transform(test_arr)
test_mm_scaled.tolist() 
# [[0.0], [0.1], [0.2], [0.3], [0.4], [0.5]]

[[0.0], [0.2], [0.4], [0.6000000000000001], [0.8], [1.0]]

In [39]:
# 테스트 데이터로 다시 Scaler를 fit()한 다음 transform 한 경우
# mmscaler.fit(test_arr)
# test_mm_scaled = mmscaler.transform(test_arr)
# test_mm_scaled.tolist()
# [[0.0], [0.2], [0.4], [0.6], [0.8], [1.0]]

[[0.0], [0.2], [0.4], [0.6000000000000001], [0.8], [1.0]]

#### 테스트 데이터 피처 스케일링 시, 반드시!!! 학습 데이터를 기준으로 fit한 Scaler로 transform해야 한다